version: 2

project_name: reaper

before:
  hooks:
    - go mod tidy
    - make build

builds:
  - main: ./cmd/reaper
    ldflags:
    - -X 'github.com/ghostsecurity/reaper/version.Version={{.Version}}' -X 'github.com/ghostsecurity/reaper/version.Date={{.Date}}' -s -w
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: ['tar.gz']
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
    - goos: windows
      formats: ['zip']

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: ghostsecurity
    name: reaper
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
