builds:
  - binary: reaper
    hooks:
      pre:
        - mkdir -p frontend/dist
        - touch frontend/dist/nothing.txt
      post:
        - wails build --platform "{{ .Os }}/{{ .Arch }}" --ldflags "-X github.com/ghostsecurity/reaper/version.Version={{.Tag}} -s -w" -o "{{ .Path }}" --debug 
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

archives:
  - format: binary
    name_template: "{{ .Binary}}-{{ .Os }}-{{ .Arch }}"

      #release:
      #  prerelease: auto
      #  github:
      #    owner: ghostsecurity
      #    name: reaper

