// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Confirm(arg1, arg2) {
  return window['go']['backend']['App']['Confirm'](arg1, arg2);
}

export function CreateNode(arg1) {
  return window['go']['backend']['App']['CreateNode'](arg1);
}

export function CreateWorkflow() {
  return window['go']['backend']['App']['CreateWorkflow']();
}

export function CreateWorkflowFromRequest(arg1) {
  return window['go']['backend']['App']['CreateWorkflowFromRequest'](arg1);
}

export function CreateWorkspace(arg1) {
  return window['go']['backend']['App']['CreateWorkspace'](arg1);
}

export function DeleteWorkspace(arg1) {
  return window['go']['backend']['App']['DeleteWorkspace'](arg1);
}

export function Error(arg1, arg2) {
  return window['go']['backend']['App']['Error'](arg1, arg2);
}

export function GenerateID() {
  return window['go']['backend']['App']['GenerateID']();
}

export function GetSettings() {
  return window['go']['backend']['App']['GetSettings']();
}

export function GetWorkspaces() {
  return window['go']['backend']['App']['GetWorkspaces']();
}

export function HighlightBody(arg1, arg2) {
  return window['go']['backend']['App']['HighlightBody'](arg1, arg2);
}

export function HighlightHTTP(arg1) {
  return window['go']['backend']['App']['HighlightHTTP'](arg1);
}

export function IgnoreThisUsedBindings(arg1) {
  return window['go']['backend']['App']['IgnoreThisUsedBindings'](arg1);
}

export function LoadWorkspace(arg1) {
  return window['go']['backend']['App']['LoadWorkspace'](arg1);
}

export function Notify(arg1, arg2) {
  return window['go']['backend']['App']['Notify'](arg1, arg2);
}

export function RunWorkflow(arg1) {
  return window['go']['backend']['App']['RunWorkflow'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['backend']['App']['SaveSettings'](arg1);
}

export function SaveWorkspace(arg1) {
  return window['go']['backend']['App']['SaveWorkspace'](arg1);
}

export function SelectFile(arg1) {
  return window['go']['backend']['App']['SelectFile'](arg1);
}

export function SetWorkspace(arg1) {
  return window['go']['backend']['App']['SetWorkspace'](arg1);
}

export function StartProxy() {
  return window['go']['backend']['App']['StartProxy']();
}

export function StopProxy() {
  return window['go']['backend']['App']['StopProxy']();
}

export function StopWorkflow(arg1) {
  return window['go']['backend']['App']['StopWorkflow'](arg1);
}

export function Warn(arg1, arg2) {
  return window['go']['backend']['App']['Warn'](arg1, arg2);
}
