name: "📜 Documentation Suggestion"
description: "Suggest a new page, section, or edit for an existing page."
title: "[Suggestion]: "
labels: ["type: documentation"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: |
        A clear and concise summary of what we should add.
      placeholder: |
        Example:
        Add an example for how to use the Scan feature.
    validations:
      required: true
  - type: input
    id: page
    attributes:
      label: Page
      description: |
        Which page is this about?
      placeholder: |
        Explore
    validations:
      required: false
  - type: textarea
    id: details
    attributes:
      label: Details
      description: |
        Please provide a explanation for what you're suggesting.
      placeholder: |
        Example:
        I think it would be helpful to have an example that walks through how to use the Scan feature in Reaper.
    validations:
      required: true
