// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Confirm(arg1, arg2) {
  return window['go']['app']['App']['Confirm'](arg1, arg2);
}

export function CreateWorkspace(arg1) {
  return window['go']['app']['App']['CreateWorkspace'](arg1);
}

export function DeleteWorkspace(arg1) {
  return window['go']['app']['App']['DeleteWorkspace'](arg1);
}

export function Error(arg1, arg2) {
  return window['go']['app']['App']['Error'](arg1, arg2);
}

export function GenerateID() {
  return window['go']['app']['App']['GenerateID']();
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function GetWorkspaces() {
  return window['go']['app']['App']['GetWorkspaces']();
}

export function HighlightBody(arg1, arg2) {
  return window['go']['app']['App']['HighlightBody'](arg1, arg2);
}

export function HighlightHTTP(arg1) {
  return window['go']['app']['App']['HighlightHTTP'](arg1);
}

export function LoadWorkspace(arg1) {
  return window['go']['app']['App']['LoadWorkspace'](arg1);
}

export function Notify(arg1, arg2) {
  return window['go']['app']['App']['Notify'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['app']['App']['SaveSettings'](arg1);
}

export function SaveWorkspace(arg1) {
  return window['go']['app']['App']['SaveWorkspace'](arg1);
}

export function SetWorkspace(arg1) {
  return window['go']['app']['App']['SetWorkspace'](arg1);
}

export function StartProxy() {
  return window['go']['app']['App']['StartProxy']();
}

export function StopProxy() {
  return window['go']['app']['App']['StopProxy']();
}

export function Warn(arg1, arg2) {
  return window['go']['app']['App']['Warn'](arg1, arg2);
}
