// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {workspace} from '../models';
import {settings} from '../models';

export function CreateWorkspace(arg1:workspace.Workspace):Promise<workspace.Workspace>;

export function DeleteWorkspace(arg1:string):Promise<void>;

export function GetSettings():Promise<settings.Settings>;

export function GetWorkspaces():Promise<Array<workspace.Workspace>>;

export function HighlightCode(arg1:string):Promise<string>;

export function LoadWorkspace(arg1:string):Promise<workspace.Workspace>;

export function SaveSettings(arg1:settings.Settings):Promise<void>;

export function SaveWorkspace(arg1:workspace.Workspace):Promise<void>;

export function SetWorkspace(arg1:workspace.Workspace):Promise<void>;

export function StartProxy():Promise<void>;

export function StopProxy():Promise<void>;
