name: snapshot

on:
  pull_request:
  push:
    tags:
      - v*

jobs:
  build:
    name: snapshot
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        arch: [ amd64, arm64 ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum

            #      - name: Import GPG key
            #        id: import_gpg
            #        uses: crazy-max/ghaction-import-gpg@v5.2.0
            #        with:
            #          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
            #          passphrase: ${{ secrets.GPG_PASSPHRASE }}
  
            
      - name: Install wails
        run: make wails && wails doctor

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev

      - name: dist
        run: mkdir -p dist

      - name: prep vars
        run: |
          OS=${{ matrix.os }}
          OS=${OS//-latest}
          [[ "$OS" = "macos" ]] && OS=darwin
          [[ "$OS" = "ubuntu" ]] && OS=linux
          echo W_OS=${OS} >> $GITHUB_ENV
          echo W_ARCH=${{ matrix.arch }} >> $GITHUB_ENV
          echo "W_PLATFORM=${OS}/${{ matrix.arch }}" >> $GITHUB_ENV

      - name: build
        run: wails build --platform "${W_PLATFORM}" --ldflags "-X github.com/ghostsecurity/reaper/version.Version=${GITHUB_REF#refs/*/} -s -w" -o "dist/reaper-${W_OS}-${W_ARCH}" --debug 

      - name: publish
        run: ls -la dist/
